// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkKY6me_74HRaj26IHcQr26H1ROeiFKv8',
    appId: '1:511608325453:web:24b4a4757ac31df58ba304',
    messagingSenderId: '511608325453',
    projectId: 'breakfast-102e0',
    authDomain: 'breakfast-102e0.firebaseapp.com',
    storageBucket: 'breakfast-102e0.firebasestorage.app',
    measurementId: 'G-K7YNGQ5B46',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGapJ5KE3BjDb3p8eleqjF1wWq62PvvY8',
    appId: '1:511608325453:android:f7ef37e204ceb7ad8ba304',
    messagingSenderId: '511608325453',
    projectId: 'breakfast-102e0',
    storageBucket: 'breakfast-102e0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeB3ONij8h2XH6kQIcuSnfflbIJnnAHyo',
    appId: '1:511608325453:ios:5178ab4ec4dd35398ba304',
    messagingSenderId: '511608325453',
    projectId: 'breakfast-102e0',
    storageBucket: 'breakfast-102e0.firebasestorage.app',
    iosBundleId: 'com.example.breakfastBuddy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeB3ONij8h2XH6kQIcuSnfflbIJnnAHyo',
    appId: '1:511608325453:ios:5178ab4ec4dd35398ba304',
    messagingSenderId: '511608325453',
    projectId: 'breakfast-102e0',
    storageBucket: 'breakfast-102e0.firebasestorage.app',
    iosBundleId: 'com.example.breakfastBuddy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkKY6me_74HRaj26IHcQr26H1ROeiFKv8',
    appId: '1:511608325453:web:8120e93796fce9ed8ba304',
    messagingSenderId: '511608325453',
    projectId: 'breakfast-102e0',
    authDomain: 'breakfast-102e0.firebaseapp.com',
    storageBucket: 'breakfast-102e0.firebasestorage.app',
    measurementId: 'G-H35QHWDXBB',
  );
}
